import type { Metadata } from 'next';
import { BIZ_UDPGothic, BIZ_UDPMincho } from 'next/font/google';
import './globals.css';

import AppHeader from '@/components/AppHeader';
import AppFooter from '@/components/AppFooter';

export const bizUdpMincho = BIZ_UDPMincho({ weight: '700',
  preload: false });
export const bizUdpGothic = BIZ_UDPGothic({ weight: [
  '400',
  '700'
],
preload: false });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout ({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={bizUdpGothic.className}>
        <AppHeader />
        {children}
        <AppFooter />
      </body>
    </html>
  );
}
